package dto;
// Generated 09-09-2018 17:10:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

    private Integer idEquipo;
    private Liga liga;
    private TipoLiga tipoLiga;
    private Usuario usuario;
    private String nombreEquipo;
    private byte estadoEquipo;
    private Set<Integrantes> integranteses = new HashSet<Integrantes>(0);

    public Equipo() {
    }

    public Equipo(Liga liga, TipoLiga tipoLiga, Usuario usuario, String nombreEquipo, byte estadoEquipo) {
        this.liga = liga;
        this.tipoLiga = tipoLiga;
        this.usuario = usuario;
        this.nombreEquipo = nombreEquipo;
        this.estadoEquipo = estadoEquipo;
    }

    public Equipo(Liga liga, TipoLiga tipoLiga, Usuario usuario, String nombreEquipo, byte estadoEquipo, Set<Integrantes> integranteses) {
        this.liga = liga;
        this.tipoLiga = tipoLiga;
        this.usuario = usuario;
        this.nombreEquipo = nombreEquipo;
        this.estadoEquipo = estadoEquipo;
        this.integranteses = integranteses;
    }

    public Integer getIdEquipo() {
        return this.idEquipo;
    }

    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }

    public Liga getLiga() {
        return this.liga;
    }

    public void setLiga(Liga liga) {
        this.liga = liga;
    }

    public TipoLiga getTipoLiga() {
        return this.tipoLiga;
    }

    public void setTipoLiga(TipoLiga tipoLiga) {
        this.tipoLiga = tipoLiga;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNombreEquipo() {
        return this.nombreEquipo;
    }

    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }

    public byte getEstadoEquipo() {
        return this.estadoEquipo;
    }

    public void setEstadoEquipo(byte estadoEquipo) {
        this.estadoEquipo = estadoEquipo;
    }

    public Set<Integrantes> getIntegranteses() {
        return this.integranteses;
    }

    public void setIntegranteses(Set<Integrantes> integranteses) {
        this.integranteses = integranteses;
    }

}
