package dto;
// Generated 09-09-2018 17:10:23 by Hibernate Tools 4.3.1



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer idImagen;
     private Integer equipoIdEquipo;
     private String integrantesRutIntegrante;
     private Integer ligaIdLiga;
     private String imagen;

    public Imagen() {
    }

	
    public Imagen(String imagen) {
        this.imagen = imagen;
    }
    public Imagen(Integer equipoIdEquipo, String integrantesRutIntegrante, Integer ligaIdLiga, String imagen) {
       this.equipoIdEquipo = equipoIdEquipo;
       this.integrantesRutIntegrante = integrantesRutIntegrante;
       this.ligaIdLiga = ligaIdLiga;
       this.imagen = imagen;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public Integer getEquipoIdEquipo() {
        return this.equipoIdEquipo;
    }
    
    public void setEquipoIdEquipo(Integer equipoIdEquipo) {
        this.equipoIdEquipo = equipoIdEquipo;
    }
    public String getIntegrantesRutIntegrante() {
        return this.integrantesRutIntegrante;
    }
    
    public void setIntegrantesRutIntegrante(String integrantesRutIntegrante) {
        this.integrantesRutIntegrante = integrantesRutIntegrante;
    }
    public Integer getLigaIdLiga() {
        return this.ligaIdLiga;
    }
    
    public void setLigaIdLiga(Integer ligaIdLiga) {
        this.ligaIdLiga = ligaIdLiga;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


