package dto;
// Generated 09-09-2018 23:17:02 by Hibernate Tools 4.3.1



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private String imagen;
     private Equipo equipo;
     private Integrantes integrantes;
     private Liga liga;

    public Imagen() {
    }

	
    public Imagen(String imagen, Integrantes integrantes, Liga liga) {
        this.imagen = imagen;
        this.integrantes = integrantes;
        this.liga = liga;
    }
    public Imagen(String imagen, Equipo equipo, Integrantes integrantes, Liga liga) {
       this.imagen = imagen;
       this.equipo = equipo;
       this.integrantes = integrantes;
       this.liga = liga;
    }
   
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Integrantes getIntegrantes() {
        return this.integrantes;
    }
    
    public void setIntegrantes(Integrantes integrantes) {
        this.integrantes = integrantes;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }




}


