package dto;
// Generated 04-09-2018 13:49:56 by Hibernate Tools 4.3.1



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer idImagen;
     private Equipo equipo;
     private Integrantes integrantes;
     private Liga liga;
     private String imagen;

    public Imagen() {
    }

	
    public Imagen(String imagen) {
        this.imagen = imagen;
    }
    public Imagen(Equipo equipo, Integrantes integrantes, Liga liga, String imagen) {
       this.equipo = equipo;
       this.integrantes = integrantes;
       this.liga = liga;
       this.imagen = imagen;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Integrantes getIntegrantes() {
        return this.integrantes;
    }
    
    public void setIntegrantes(Integrantes integrantes) {
        this.integrantes = integrantes;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


