package dto;
// Generated 09-09-2018 17:10:23 by Hibernate Tools 4.3.1



/**
 * Integrantes generated by hbm2java
 */
public class Integrantes  implements java.io.Serializable {


     private String rutIntegrante;
     private Equipo equipo;
     private String nombreIntegrante;
     private String nick;
     private byte estadoInt;

    public Integrantes() {
    }

    public Integrantes(String rutIntegrante, Equipo equipo, String nombreIntegrante, String nick, byte estadoInt) {
       this.rutIntegrante = rutIntegrante;
       this.equipo = equipo;
       this.nombreIntegrante = nombreIntegrante;
       this.nick = nick;
       this.estadoInt = estadoInt;
    }
   
    public String getRutIntegrante() {
        return this.rutIntegrante;
    }
    
    public void setRutIntegrante(String rutIntegrante) {
        this.rutIntegrante = rutIntegrante;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombreIntegrante() {
        return this.nombreIntegrante;
    }
    
    public void setNombreIntegrante(String nombreIntegrante) {
        this.nombreIntegrante = nombreIntegrante;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public byte getEstadoInt() {
        return this.estadoInt;
    }
    
    public void setEstadoInt(byte estadoInt) {
        this.estadoInt = estadoInt;
    }




}


