package dto;
// Generated 04-09-2018 13:49:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Integrantes generated by hbm2java
 */
public class Integrantes  implements java.io.Serializable {


     private String rutIntegrante;
     private Equipo equipo;
     private String nombreIntegrante;
     private String nick;
     private byte estadoInt;
     private Set<Imagen> imagens = new HashSet<Imagen>(0);

    public Integrantes() {
    }

	
    public Integrantes(String rutIntegrante, Equipo equipo, String nombreIntegrante, String nick, byte estadoInt) {
        this.rutIntegrante = rutIntegrante;
        this.equipo = equipo;
        this.nombreIntegrante = nombreIntegrante;
        this.nick = nick;
        this.estadoInt = estadoInt;
    }
    public Integrantes(String rutIntegrante, Equipo equipo, String nombreIntegrante, String nick, byte estadoInt, Set<Imagen> imagens) {
       this.rutIntegrante = rutIntegrante;
       this.equipo = equipo;
       this.nombreIntegrante = nombreIntegrante;
       this.nick = nick;
       this.estadoInt = estadoInt;
       this.imagens = imagens;
    }
   
    public String getRutIntegrante() {
        return this.rutIntegrante;
    }
    
    public void setRutIntegrante(String rutIntegrante) {
        this.rutIntegrante = rutIntegrante;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombreIntegrante() {
        return this.nombreIntegrante;
    }
    
    public void setNombreIntegrante(String nombreIntegrante) {
        this.nombreIntegrante = nombreIntegrante;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public byte getEstadoInt() {
        return this.estadoInt;
    }
    
    public void setEstadoInt(byte estadoInt) {
        this.estadoInt = estadoInt;
    }
    public Set<Imagen> getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set<Imagen> imagens) {
        this.imagens = imagens;
    }




}


