package dto;
// Generated 09-09-2018 23:17:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Liga generated by hbm2java
 */
public class Liga  implements java.io.Serializable {


     private String nombreLiga;
     private TipoLiga tipoLiga;
     private Date fechaInicio;
     private Date fechaTermino;
     private String lugar;
     private Set<Imagen> imagens = new HashSet<Imagen>(0);
     private Set<Equipo> equipos = new HashSet<Equipo>(0);
     private Set<LigaResultado> ligaResultados = new HashSet<LigaResultado>(0);

    public Liga() {
    }

	
    public Liga(String nombreLiga, TipoLiga tipoLiga, Date fechaInicio, Date fechaTermino, String lugar) {
        this.nombreLiga = nombreLiga;
        this.tipoLiga = tipoLiga;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
        this.lugar = lugar;
    }
    public Liga(String nombreLiga, TipoLiga tipoLiga, Date fechaInicio, Date fechaTermino, String lugar, Set<Imagen> imagens, Set<Equipo> equipos, Set<LigaResultado> ligaResultados) {
       this.nombreLiga = nombreLiga;
       this.tipoLiga = tipoLiga;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.lugar = lugar;
       this.imagens = imagens;
       this.equipos = equipos;
       this.ligaResultados = ligaResultados;
    }
   
    public String getNombreLiga() {
        return this.nombreLiga;
    }
    
    public void setNombreLiga(String nombreLiga) {
        this.nombreLiga = nombreLiga;
    }
    public TipoLiga getTipoLiga() {
        return this.tipoLiga;
    }
    
    public void setTipoLiga(TipoLiga tipoLiga) {
        this.tipoLiga = tipoLiga;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set<Imagen> getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set<Imagen> imagens) {
        this.imagens = imagens;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }
    public Set<LigaResultado> getLigaResultados() {
        return this.ligaResultados;
    }
    
    public void setLigaResultados(Set<LigaResultado> ligaResultados) {
        this.ligaResultados = ligaResultados;
    }




}


