package dto;
// Generated 09-09-2018 17:10:23 by Hibernate Tools 4.3.1



/**
 * LigaResultadoId generated by hbm2java
 */
public class LigaResultadoId  implements java.io.Serializable {


     private int ligaIdLiga;
     private int resultadosIdResultados;

    public LigaResultadoId() {
    }

    public LigaResultadoId(int ligaIdLiga, int resultadosIdResultados) {
       this.ligaIdLiga = ligaIdLiga;
       this.resultadosIdResultados = resultadosIdResultados;
    }
   
    public int getLigaIdLiga() {
        return this.ligaIdLiga;
    }
    
    public void setLigaIdLiga(int ligaIdLiga) {
        this.ligaIdLiga = ligaIdLiga;
    }
    public int getResultadosIdResultados() {
        return this.resultadosIdResultados;
    }
    
    public void setResultadosIdResultados(int resultadosIdResultados) {
        this.resultadosIdResultados = resultadosIdResultados;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigaResultadoId) ) return false;
		 LigaResultadoId castOther = ( LigaResultadoId ) other; 
         
		 return (this.getLigaIdLiga()==castOther.getLigaIdLiga())
 && (this.getResultadosIdResultados()==castOther.getResultadosIdResultados());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLigaIdLiga();
         result = 37 * result + this.getResultadosIdResultados();
         return result;
   }   


}


