package dto;
// Generated 09-09-2018 23:17:02 by Hibernate Tools 4.3.1



/**
 * LigaResultadoId generated by hbm2java
 */
public class LigaResultadoId  implements java.io.Serializable {


     private String ligaNombreLiga;
     private int resultadosIdResultados;

    public LigaResultadoId() {
    }

    public LigaResultadoId(String ligaNombreLiga, int resultadosIdResultados) {
       this.ligaNombreLiga = ligaNombreLiga;
       this.resultadosIdResultados = resultadosIdResultados;
    }
   
    public String getLigaNombreLiga() {
        return this.ligaNombreLiga;
    }
    
    public void setLigaNombreLiga(String ligaNombreLiga) {
        this.ligaNombreLiga = ligaNombreLiga;
    }
    public int getResultadosIdResultados() {
        return this.resultadosIdResultados;
    }
    
    public void setResultadosIdResultados(int resultadosIdResultados) {
        this.resultadosIdResultados = resultadosIdResultados;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigaResultadoId) ) return false;
		 LigaResultadoId castOther = ( LigaResultadoId ) other; 
         
		 return ( (this.getLigaNombreLiga()==castOther.getLigaNombreLiga()) || ( this.getLigaNombreLiga()!=null && castOther.getLigaNombreLiga()!=null && this.getLigaNombreLiga().equals(castOther.getLigaNombreLiga()) ) )
 && (this.getResultadosIdResultados()==castOther.getResultadosIdResultados());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLigaNombreLiga() == null ? 0 : this.getLigaNombreLiga().hashCode() );
         result = 37 * result + this.getResultadosIdResultados();
         return result;
   }   


}


