package dto;
// Generated 01-09-2018 17:54:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoLiga generated by hbm2java
 */
public class TipoLiga  implements java.io.Serializable {


     private Integer idtipoLiga;
     private String descripcion;
     private Set<Liga> ligas = new HashSet<Liga>(0);
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public TipoLiga() {
    }

	
    public TipoLiga(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoLiga(String descripcion, Set<Liga> ligas, Set<Equipo> equipos) {
       this.descripcion = descripcion;
       this.ligas = ligas;
       this.equipos = equipos;
    }
   
    public Integer getIdtipoLiga() {
        return this.idtipoLiga;
    }
    
    public void setIdtipoLiga(Integer idtipoLiga) {
        this.idtipoLiga = idtipoLiga;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Liga> getLigas() {
        return this.ligas;
    }
    
    public void setLigas(Set<Liga> ligas) {
        this.ligas = ligas;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


