package dto;
// Generated 09-09-2018 23:17:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correoUsuario;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private String passUsuario;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Usuario() {
    }

	
    public Usuario(String correoUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String passUsuario) {
        this.correoUsuario = correoUsuario;
        this.tipoUsuario = tipoUsuario;
        this.nombreUsuario = nombreUsuario;
        this.passUsuario = passUsuario;
    }
    public Usuario(String correoUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String passUsuario, Set<Equipo> equipos) {
       this.correoUsuario = correoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.passUsuario = passUsuario;
       this.equipos = equipos;
    }
   
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


